In [1]:
from functools import cmp_to_key
import os
import pandas as pd

In [2]:
def compare_file(file1, file2):
    num1 = int(file1.split('.')[0])  
    num2 = int(file2.split('.')[0])  
    if num1 < num2:
        return -1
    elif num1 > num2:
        return 1
    else:
        return 0
def pb_read_appendix1(path="./Problem B/Appendix 1"):
   data=[]
   lower_range=0
   upper_range=2881
   for (_, _, filenames) in os.walk(path):
      temp_save=filenames.copy()
      for idx, ff in enumerate(filenames):
          if ff.startswith("~"):
              temp_save.remove(ff)
      filenames=sorted(temp_save, key=cmp_to_key(compare_file))
      for filename in filenames:
         excel_instance=pd.read_excel(os.path.join(path, filename), sheet_name='Sheet1')
         if len(excel_instance["Var1"].to_list())<(upper_range-lower_range+1):
             continue
         data.append({})
         data[-1]["date"]=[i for i in excel_instance["Var1"].to_list()]
         data[-1]["time"]=[i for i in excel_instance["Var2"].to_list()]
         data[-1]["x"]=[i for i in excel_instance["Var3"].to_list()]
         data[-1]["y"]=[i for i in excel_instance["Var4"].to_list()]
         data[-1]["z"]=[i for i in excel_instance["Var5"].to_list()]
         print(f"{filename} len:{len(data[-1]["date"])}")
   
   for sensor in data:
       sensor["date"]=sensor["date"][lower_range:upper_range]
       sensor["time"]=sensor["time"][lower_range:upper_range]
       sensor["x"]=sensor["x"][lower_range:upper_range]
       sensor["y"]=sensor["y"][lower_range:upper_range]
       sensor["z"]=sensor["z"][lower_range:upper_range]
   return data

In [3]:
appendix1=pb_read_appendix1() #读取所有传感器的数据到一个字典里 只取24:00到4:00的数据！

1.xlsx len:4310
2.xlsx len:4310
3.xlsx len:4310
4.xlsx len:4310
5.xlsx len:4310
6.xlsx len:4310
7.xlsx len:4310
8.xlsx len:4310
9.xlsx len:4310
10.xlsx len:4310
11.xlsx len:4310
12.xlsx len:4310
13.xlsx len:4310
14.xlsx len:4310
15.xlsx len:4310
16.xlsx len:4310
17.xlsx len:4310
18.xlsx len:4310
19.xlsx len:4310
20.xlsx len:4310
21.xlsx len:4310
22.xlsx len:4310
23.xlsx len:4310
24.xlsx len:4310
25.xlsx len:4310
26.xlsx len:4310
27.xlsx len:4310
28.xlsx len:4310
29.xlsx len:4310
30.xlsx len:4310
31.xlsx len:4310
32.xlsx len:4310
33.xlsx len:4310
34.xlsx len:4310
35.xlsx len:4310
36.xlsx len:4310
37.xlsx len:4310
38.xlsx len:4310
39.xlsx len:4310
40.xlsx len:4310
41.xlsx len:4310
42.xlsx len:4310
43.xlsx len:4310
44.xlsx len:4310
45.xlsx len:4310
46.xlsx len:4310
47.xlsx len:4310
48.xlsx len:4310
49.xlsx len:4310
50.xlsx len:4310
51.xlsx len:4310
52.xlsx len:4310
53.xlsx len:4310
54.xlsx len:4310
55.xlsx len:4310
56.xlsx len:4310
57.xlsx len:4310
58.xlsx len:4310
59.xlsx len:4310
60.xls

In [4]:
appendix1[0]["x"]

[30883.092,
 30883.07,
 30883.044,
 30883.108,
 30882.971,
 30883.06,
 30883.069,
 30882.991,
 30883.008,
 30883.025,
 30883.025,
 30883.01,
 30883.078,
 30883.089,
 30883.158,
 30883.147,
 30883.046,
 30883.004,
 30883.002,
 30882.929,
 30882.931,
 30882.872,
 30883.046,
 30883.212,
 30883.252,
 30883.178,
 30883.128,
 30883.005,
 30883.003,
 30882.93,
 30882.992,
 30883.095,
 30883.086,
 30883.0,
 30882.958,
 30882.989,
 30882.98,
 30883.038,
 30882.956,
 30882.916,
 30883.002,
 30883.081,
 30883.033,
 30883.023,
 30882.949,
 30882.902,
 30882.91,
 30882.878,
 30882.919,
 30882.893,
 30883.002,
 30882.938,
 30882.944,
 30883.0,
 30883.022,
 30882.921,
 30882.934,
 30883.0,
 30883.086,
 30883.056,
 30883.032,
 30883.07,
 30883.087,
 30883.155,
 30883.134,
 30883.151,
 30883.66,
 30883.197,
 30883.203,
 30883.193,
 30883.221,
 30883.242,
 30883.184,
 30882.583,
 30882.781,
 30882.895,
 30883.079,
 30883.247,
 30883.245,
 30883.289,
 30883.269,
 30883.229,
 30883.186,
 30882.704,
 30883

In [5]:
print(len(appendix1[0]["x"]))

2881


# 读取格式
读取出来是一个array,每个array是每个传感器的信息
## keys 
1. date$\Rightarrow$一个包含不同点日期的array
2. time$\Rightarrow$一个包含对应时间戳的点
3. x$\Rightarrow$该时间戳下的x值
4. y$\Rightarrow$该时间戳下的y值
5. z$\Rightarrow$该时间戳下的z值

In [6]:
import torch 
import numpy as np
device="cuda"

In [7]:
xs=[]
ys=[]
zs=[]
for sensor in appendix1:
    xs.append([x-sensor["x"][0] for x in sensor["x"]])
    ys.append([y-sensor["y"][0] for y in sensor["y"]])
    zs.append([z-sensor["z"][0] for z in sensor["z"]])
xs=np.array(xs)
ys=np.array(ys)
zs=np.array(zs)
xs=torch.from_numpy(xs).to(device)
ys=torch.from_numpy(ys).to(device)
zs=torch.from_numpy(zs).to(device)


In [11]:
import json
dumped_xs=xs.transpose(0,1).cpu().numpy().tolist()
dumped_ys=ys.transpose(0,1).cpu().numpy().tolist()
dumped_zs=zs.transpose(0,1).cpu().numpy().tolist()
dumped_dict={}
for time_idx in range(len(dumped_xs)):
    dumped_dict[time_idx]={"x":dumped_xs[time_idx], "y":dumped_ys[time_idx],"z":dumped_zs[time_idx]}
json.dump(dumped_dict,open("dumped_full.json","w+"))

In [ ]:
from sklearn.neighbors import KDTree, BallTree


In [ ]:
num_sensors=len(appendix1)
num_time_stamps=len(appendix1[0]["time"])
xyzs=torch.stack([xs,ys,zs])
xyzs=xyzs.permute(2,1,0)
print(xyzs.shape)
for idx_time in range(xyzs.shape[0]):
    point_array=xyzs[idx_time][:][:].cpu().numpy()
    center_point=np.mean(point_array, 0).reshape(1,-1)
    print(center_point)
    tree=BallTree(point_array)

    dist, ind=tree.query(center_point)
    print(f"Index of nearest neighbor: {ind[0][0]}")
    print(f"Distance to nearest neighbor: {dist[0][0]}+1")


torch.Size([2881, 348, 3])
[[0. 0. 0.]]
Index of nearest neighbor: 1
Distance to nearest neighbor: 0.0+1
[[-0.03659483 -0.02598276 -0.27165805]]
Index of nearest neighbor: 40
Distance to nearest neighbor: 0.03264982817321075+1
[[-0.10223276 -0.00983908 -0.36174713]]
Index of nearest neighbor: 329
Distance to nearest neighbor: 0.019155452827784754+1
[[-0.0598046  -0.05470115 -0.05943103]]
Index of nearest neighbor: 209
Distance to nearest neighbor: 0.008158104179263605+1
[[-0.14241667 -0.02777586 -0.19373276]]
Index of nearest neighbor: 119
Distance to nearest neighbor: 0.03230435155126691+1
[[-0.12220115 -0.08669828 -0.31760345]]
Index of nearest neighbor: 41
Distance to nearest neighbor: 0.023350557207932134+1
[[-0.13283046 -0.09171839 -0.15350862]]
Index of nearest neighbor: 319
Distance to nearest neighbor: 0.029422781580709614+1
[[-0.15413793 -0.08990805 -0.20595977]]
Index of nearest neighbor: 253
Distance to nearest neighbor: 0.021068724876474255+1
[[-0.14168391 -0.12441954 -0.02

In [246]:
result1=pd.DataFrame(data={"Time":appendix1[0]["time"], "Best sensor":best_sensors})

In [249]:
with pd.ExcelWriter("Problem B_1.xlsx", engine="openpyxl") as writer:
    result1.to_excel(writer)